require("core.plugin_config.autopairs")
require("core.plugin_config.cmp")
require("core.plugin_config.comment")
require("core.plugin_config.exrc")
require("core.plugin_config.gitsigns")
require("core.plugin_config.gruvbox")
require("core.plugin_config.harpoon")
require("core.plugin_config.indent_blackline")
require("core.plugin_config.lsp_config")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tmux-navitaion")
require("core.plugin_config.snippy")
require("core.plugin_config.telescope")
require("core.plugin_config.tree")
require("core.plugin_config.treesitter")

